name: lcs_new_age
description: A satirical game about American politics.
publish_to: 'none'
version: 1.1.10

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  format: ^1.6.0
  json_annotation: ^4.9.0
  file_picker: ^10.3.3
  cupertino_icons: ^1.0.8
  web: ^1.1.1
  markdown_widget: ^2.3.2
  pixel_snap: ^0.1.5
  xml: ^6.5.0
  flutter_svg: ^2.0.17
  collection: ^1.19.0
  shared_preferences: ^2.5.1
  file_saver: ^0.3.1
  source_map_stack_trace: ^2.1.2
  source_maps: ^0.10.13
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

flutter:
  assets:
   - assets/xml/
   - assets/flags/
   - assets/maps/
   - assets/art/
   - assets/changelog.md
  uses-material-design: true
  fonts:
   - family: SourceCodePro
     fonts:
      - asset: fonts/SourceCodePro-Regular.ttf
